/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sims.salemanager;

import com.formdev.flatlaf.ui.FlatTextFieldUI;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class SALEMANAGERFRAME extends javax.swing.JFrame {

    private boolean isMouseOver = false;
    private String usernameManager;
    private String passwordManager;

    public SALEMANAGERFRAME() {
        initComponents();

        ChangeScreen changeScreenController;
        try {
            changeScreenController = new ChangeScreen(jPanel6);
            changeScreenController.setView(jpnProfile, jlbProfile);
            List<ListSaleManagerForm> listItem = new ArrayList<>();
            listItem.add(new ListSaleManagerForm("EXCEPTIONS", jpnExceptions, jlbExceptions));
            listItem.add(new ListSaleManagerForm("BILL", jpnBill, jBill));
            listItem.add(new ListSaleManagerForm("MONEY", jpnMoney, jlbMoney));
//            listItem.add(new ListSaleManagerForm("INFORM", jpnInform, jInForm));
            listItem.add(new ListSaleManagerForm("PROFILE1", jpnProfile, jlbProfile));
            listItem.add(new ListSaleManagerForm("ITEM TAKE BACK", jpnITB, jItemTakeBack));
            listItem.add(new ListSaleManagerForm("SIGN OUT", jpnLogOut, jlbLogOut));

            changeScreenController.setEvent(listItem);
        } catch (SQLException ex) {
            Logger.getLogger(SALEMANAGERFRAME.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SALEMANAGERFRAME.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public SALEMANAGERFRAME(String username,String password) {
        initComponents();
        this.usernameManager=username;
        this.passwordManager=password;
        ChangeScreen changeScreenController;
        try {
            changeScreenController = new ChangeScreen(jPanel6,username,password);
            changeScreenController.setView(jpnProfile, jlbProfile);
            List<ListSaleManagerForm> listItem = new ArrayList<>();
            listItem.add(new ListSaleManagerForm("EXCEPTIONS", jpnExceptions, jlbExceptions));
            listItem.add(new ListSaleManagerForm("BILL", jpnBill, jBill));
            listItem.add(new ListSaleManagerForm("MONEY", jpnMoney, jlbMoney));
//            listItem.add(new ListSaleManagerForm("INFORM", jpnInform, jInForm));
            listItem.add(new ListSaleManagerForm("PROFILE1", jpnProfile, jlbProfile));
            listItem.add(new ListSaleManagerForm("ITEM TAKE BACK", jpnITB, jItemTakeBack));
            listItem.add(new ListSaleManagerForm("SIGN OUT", jpnLogOut, jlbLogOut));

            changeScreenController.setEvent(listItem);
        } catch (SQLException ex) {
            Logger.getLogger(SALEMANAGERFRAME.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SALEMANAGERFRAME.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpnProfile = new javax.swing.JPanel();
        jlbProfile = new javax.swing.JLabel();
        jpnExceptions = new javax.swing.JPanel();
        jlbExceptions = new javax.swing.JLabel();
        jpnBill = new javax.swing.JPanel();
        jBill = new javax.swing.JLabel();
        jpnITB = new javax.swing.JPanel();
        jItemTakeBack = new javax.swing.JLabel();
        jpnMoney = new javax.swing.JPanel();
        jlbMoney = new javax.swing.JLabel();
        jpnInform = new javax.swing.JPanel();
        jInForm = new javax.swing.JLabel();
        jpnLogOut = new javax.swing.JPanel();
        jlbLogOut = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sims/icons/icons8-man-with-yellow-tie-in-jacket-50.png"))); // NOI18N
        jLabel3.setText("SALE MANAGER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel3.getAccessibleContext().setAccessibleName("   SALES MEN");

        jlbProfile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbProfile.setForeground(new java.awt.Color(0, 0, 0));
        jlbProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sims/icons/icons8-user-profile-60.png"))); // NOI18N
        jlbProfile.setText("PROFILE");

        javax.swing.GroupLayout jpnProfileLayout = new javax.swing.GroupLayout(jpnProfile);
        jpnProfile.setLayout(jpnProfileLayout);
        jpnProfileLayout.setHorizontalGroup(
            jpnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        jpnProfileLayout.setVerticalGroup(
            jpnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jlbExceptions.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbExceptions.setForeground(new java.awt.Color(0, 0, 0));
        jlbExceptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sims/icons/icons8-alert-40.png"))); // NOI18N
        jlbExceptions.setText("EXCEPTIONS");

        javax.swing.GroupLayout jpnExceptionsLayout = new javax.swing.GroupLayout(jpnExceptions);
        jpnExceptions.setLayout(jpnExceptionsLayout);
        jpnExceptionsLayout.setHorizontalGroup(
            jpnExceptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnExceptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jpnExceptionsLayout.setVerticalGroup(
            jpnExceptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnExceptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jBill.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBill.setForeground(new java.awt.Color(0, 0, 0));
        jBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sims/icons/icons8-order-completed.gif"))); // NOI18N
        jBill.setText("BILL");

        javax.swing.GroupLayout jpnBillLayout = new javax.swing.GroupLayout(jpnBill);
        jpnBill.setLayout(jpnBillLayout);
        jpnBillLayout.setHorizontalGroup(
            jpnBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBill, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnBillLayout.setVerticalGroup(
            jpnBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBill, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jItemTakeBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jItemTakeBack.setForeground(new java.awt.Color(0, 0, 0));
        jItemTakeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sims/icons/icons8-buy.gif"))); // NOI18N
        jItemTakeBack.setText("ITEM TAKE BACK");

        javax.swing.GroupLayout jpnITBLayout = new javax.swing.GroupLayout(jpnITB);
        jpnITB.setLayout(jpnITBLayout);
        jpnITBLayout.setHorizontalGroup(
            jpnITBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnITBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jItemTakeBack, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnITBLayout.setVerticalGroup(
            jpnITBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnITBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jItemTakeBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jlbMoney.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbMoney.setForeground(new java.awt.Color(0, 0, 0));
        jlbMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sims/icons/icons8-cash-60.png"))); // NOI18N
        jlbMoney.setText("MONEY");

        javax.swing.GroupLayout jpnMoneyLayout = new javax.swing.GroupLayout(jpnMoney);
        jpnMoney.setLayout(jpnMoneyLayout);
        jpnMoneyLayout.setHorizontalGroup(
            jpnMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMoneyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMoneyLayout.setVerticalGroup(
            jpnMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMoneyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jInForm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jInForm.setForeground(new java.awt.Color(0, 0, 0));
        jInForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sims/icons/icons8-increase-60.png"))); // NOI18N
        jInForm.setText("SALES-TREND GRAPH");

        javax.swing.GroupLayout jpnInformLayout = new javax.swing.GroupLayout(jpnInform);
        jpnInform.setLayout(jpnInformLayout);
        jpnInformLayout.setHorizontalGroup(
            jpnInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnInformLayout.setVerticalGroup(
            jpnInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInForm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jlbLogOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbLogOut.setForeground(new java.awt.Color(0, 0, 0));
        jlbLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sims/icons/icons8-logout-65.png"))); // NOI18N
        jlbLogOut.setText("SIGN OUT");

        javax.swing.GroupLayout jpnLogOutLayout = new javax.swing.GroupLayout(jpnLogOut);
        jpnLogOut.setLayout(jpnLogOutLayout);
        jpnLogOutLayout.setHorizontalGroup(
            jpnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnLogOutLayout.setVerticalGroup(
            jpnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpnInform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpnMoney, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnITB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpnBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpnExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnITB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnInform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SALES AND INVENTORY MANAGEMENT SYSTEM (SIMS)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SALEMANAGERFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SALEMANAGERFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SALEMANAGERFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SALEMANAGERFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SALEMANAGERFRAME().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBill;
    private javax.swing.JLabel jInForm;
    private javax.swing.JLabel jItemTakeBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jlbExceptions;
    private javax.swing.JLabel jlbLogOut;
    private javax.swing.JLabel jlbMoney;
    private javax.swing.JLabel jlbProfile;
    private javax.swing.JPanel jpnBill;
    private javax.swing.JPanel jpnExceptions;
    private javax.swing.JPanel jpnITB;
    private javax.swing.JPanel jpnInform;
    private javax.swing.JPanel jpnLogOut;
    private javax.swing.JPanel jpnMoney;
    private javax.swing.JPanel jpnProfile;
    // End of variables declaration//GEN-END:variables
}
